pages:
  image: alpine
  script:
  - cd doc
  - apk --no-cache add py3-pip python3-dev
  - pip3 install sphinx
  - apk --no-cache add make
  - make html
  - cd ..
  - mv doc/_build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master

# build:
#   image: nimlang/nim
#   script:
#   - nimble install yaml -y
#   - nim build
#   artifacts:
#     paths:
#     - lins
#     expire_in: 1 day
#   only:
# - master

build-win64:
  image: pivotaldata/centos-mingw
  script:
  - curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
  - sh init.sh -y
  - export PATH=$HOME/.nimble/bin:$PATH
  - nimble refresh -y
  - nimble install yaml -y
  - nim buildwin
  artifacts:
    paths:
    - lins
    expire_in: 1 day
  only:
  - master
