pages:
  image: alpine
  script:
  - cd doc
  - apk --no-cache add py3-pip python3-dev
  - pip3 install sphinx
  - apk --no-cache add make
  - make html
  - cd ..
  - mv doc/_build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master

build-deb64:
  image: nimlang/nim
  script:
  - nimble install yaml -y
  - nim build
  - cd build
  - chmod -r 755 deb/DEBIAN
  - sh build_deb.sh
  - cp *.deb ../
  artifacts:
    paths:
    - "*.deb"
    expire_in: 1 day
  only:
  - master

build-win64:
  image: nimlang/nim
  script:
  - apt update
  - apt install -y mingw-w64
  - nimble refresh -y
  - nimble install yaml -y
  - nim buildxwin64
  artifacts:
    paths:
    - lins.exe
    - LICENSE
    - THIRD_PARTY_LICENSES.md
    name: "lins-$(cat VERSION)-win-x86_64"
    expire_in: 1 day
  only:
  - master
