stages:
  - build

pages:
  stage: build
  image: alpine
  script:
  - cd doc
  - apk --no-cache add py3-pip python3-dev
  - pip3 install sphinx
  - apk --no-cache add make
  - make html
  - cd ..
  - mv doc/_build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - tags


build-linux-x86_64:
  stage: build
  image: nimlang/nim
  script:
  - nimble install yaml -y
  - nim build
  artifacts:
    expire_in: 5 mins
    paths:
    - lins
    - LICENSE
    - THIRD_PARTY_LICENSES.md
    name: "lins-$(cat VERSION)-linux-x86_64"
  only:
  - master


build-deb-x86_64:
  stage: build
  image: nimlang/nim
  script:
  - nimble install yaml -y
  - nim build
  - cd build
  - chmod -R 755 deb/DEBIAN
  - sh build_deb.sh
  - cp *.deb ../
  artifacts:
    expire_in: 5 mins
    paths:
    - "*.deb"
    name: "lins-$(cat VERSION)-deb-x86_64"
  only:
  - master


build-win-x86_64:
  stage: build
  image: nimlang/nim
  script:
  - apt update
  - apt install -y mingw-w64
  - nimble refresh -y
  - nimble install yaml -y
  - nim buildxwin64
  artifacts:
    expire_in: 5 mins
    paths:
    - lins.exe
    - LICENSE
    - THIRD_PARTY_LICENSES.md
    name: "lins-$(cat VERSION)-win-x86_64"
  only:
  - master
